import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

type MenuButtonProps = {
  name: string;
  description: string;
  link: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Geometry Dash Browser!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/coin.png" />
      </Head>

      <main className="w-full h-screen">
        <div className="absolute bottom-0 left-0 w-full pointer-events-none">
          <img className="sticky" src="/corner.png" width="7%" />
        </div>
        <div className="absolute left-0 w-full pointer-events-none">
          <img className="sticky scale-y-[-1]" src="/corner.png" width="7%" />
        </div>
        <div className="h-full grid place-items-center">
          <div className="grid grid-cols-4 gap-x-8 gap-y-4">
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
            <MenuButton
              name="saved"
              description="Saved Levels"
              link="./search/*?type=saved"
            />
          </div>
        </div>
      </main>
    </>
  );
};

const MenuButton = ({ name, description, link }: MenuButtonProps) => {
  return (
    <div className="hover:scale-105 transition-all">
      <a href={link}>
        <img
          className="w-[24vh]"
          src={`category-${name}.png`}
          title={description}
        />
      </a>
    </div>
  );
};

export default Home;
