import type { NextPage } from "next";
import Head from "next/head";
import { Fragment } from "react";
import { trpc } from "../utils/trpc";

type MenuButtonProps = {
  name: string;
  description: string;
  link: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Geometry Dash Browser!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/coin.png" />
      </Head>

      <main className="container mx-auto px-4 h-screen">
        <div className="w-full grid place-items-center mt-4">
          <div className="grid place-items-center">
            <img src="/gdlogo.png" className="" />
            <img className="place-self-end w-64" src="/browser.png" />
          </div>
        </div>
        <div className="grid place-items-center my-4">
          <div className="grid grid-cols-3 gap-x-4 gap-y-2">
            <MenuButtons />
          </div>
        </div>
      </main>
    </>
  );
};

const MenuButton = ({ name, description, link }: MenuButtonProps) => {
  return (
    <div className="hover:scale-105 transition-all">
      <a href={link}>
        <img className="" src={`category-${name}.png`} title={description} />
      </a>
    </div>
  );
};

const MenuButtons = () => {
  return (
    <Fragment>
      <MenuButton
        name="saved"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton name="daily" description="Daily Level" link="./daily" />
      <MenuButton
        name="weekly"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton
        name="gauntlets"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton
        name="scores"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton
        name="hof"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton
        name="packs"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
      <MenuButton
        name="search"
        description="Saved Levels"
        link="./search/*?type=saved"
      />
    </Fragment>
  );
};

export default Home;
